### ISSUE TITLE
npm run dist 失败

### ISSUE THREAD

**Issue by weisiwu** [WechatFE/vConsole#107]
![image](https://user-images.githubusercontent.com/10015884/27722885-cacaaab4-5d9c-11e7-8dfe-5edf8a151c83.png)

想 请教一下这个是怎么回事？多谢

**Comment by Maizify** [comment]
编辑 Package.json，第 9 行先改为 `"dist": "webpack"` 吧。现在跑 test 可能通不过。

**Comment by weisiwu** [comment]
修改后,确实通过编译了。
贴一个结果图  

![image](https://user-images.githubusercontent.com/10015884/27847011-b0988484-616d-11e7-9f00-9bc8139298d7.png)
