### ISSUE TITLE
对象过大时,可否限制下, 避免崩溃

### ISSUE THREAD

**Issue by cycold** [WechatFE/vConsole#109]
在vue中打印个路由对象都会崩溃😖 
既然对象过大就不打印吧, 或者只显示前几层字段啊 没必要崩溃啊
我是使用webpack插件打包的, 打包完发布到线上测试环境, 结果奔溃了,
又要重新打包上传, 特麻烦

**Comment by willnewii** [comment]
终于找到问题了...   刚才在路由里加了一句log,然后想在手机端调试时候发现崩溃了.想了半天也不知道问题在哪.
谢谢.   弱弱的问一句:你是怎么发现的? 这个崩溃,我浏览器都直接挂掉了...
