### ISSUE TITLE
新版本1.2.0貌似和jquery的ajax不兼容？

### ISSUE THREAD

**Issue by ydq** [WechatFE/vConsole#13]
页面上有个表单，代码中ajax提交
大概的代码如下：
```
var _form=$('form');
$.post(_form.attr('action'),_form.serialize(),function(json){
//...
},'json')
```
结果表单序列化的参数提交的时候一直没有导致后台一直提示400，
**去掉了vConsole之后却可以正常提交。**

而且第一个Post提交错误的提示也没在vConsole中打印出来
![image](https://cloud.githubusercontent.com/assets/8097340/15205370/3a7c7cba-1849-11e6-8480-761e7a1e7be1.png)
![image](https://cloud.githubusercontent.com/assets/8097340/15205378/449d7852-1849-11e6-8042-289d0cedd116.png)

**Comment by Joey-93** [comment]
XMLHttpRequest.send问题。

可以尝试在源文件vconsole.js 170行.
```
window.XMLHttpRequest.prototype.send = function() {
    var that = this;
    that._startTime = +new Date();
    setTimeout(function() {
      _send.apply(that, arguments);
    }, 1);
  };
```
修改为
```
window.XMLHttpRequest.prototype.send = function() {
    var that = this,varguments = arguments;
    that._startTime = +new Date();
    setTimeout(function() {
      _send.apply(that, varguments);
    }, 1);
  };
```
然后自己编译一遍。

如果想偷懒，直接修改vconsole.min.js文件。搜索e.apply，找到window.XMLHttpRequest.prototype.send，按照上面的方法修改一遍即可，省去编译过程。

不过还是等修复吧...

**Comment by Maizify** [comment]
确实有问题，感谢反馈~

**Comment by Maizify** [comment]
v1.2.1已修复。
