### ISSUE TITLE
vconsole复写XMLHttpRequest的send方法会导致post的数据丢失

### ISSUE THREAD

**Issue by Joey-93** [WechatFE/vConsole#14]
大概在173行处.

<code>
    setTimeout(function() {
      _send.apply(that, arguments);
    }, 1);
</code>

貌似arguments的使用有点问题，获取到的是seTimeout的回调函数arguments，而不是原本XMLHttpRequest的send方法arguments?

**Comment by Maizify** [comment]
确实有问题，有待修复……

**Comment by Maizify** [comment]
v1.2.1已修复。
