### ISSUE TITLE
requirejs引入vconsole后ajax方式无法传递参数

### ISSUE THREAD

**Issue by CharlesSong** [WechatFE/vConsole#19]
requirejs引入vconsole后ajax方式无法传递参数

**Comment by Maizify** [comment]
直接引入的话，是否正常？

**Comment by CharlesSong** [comment]
直接引入也不行，jquery2.2.0
`$.ajax({
				type: "post",
				data: param,
				url: url,
				timeout: 30000,
				async: true,
				dataType: 'json'
			})`

**Comment by Maizify** [comment]
请检查一下 vConsole 的版本是否是最新的，v1.2.1已经修复了这个问题，目前最新版本是v1.3.0。

**Comment by CharlesSong** [comment]
替换成最新版本已经正常了，谢谢，就是显示的vConsole如果可以移动位置就完美了，放在右下角有可能挡住其他东西

**Comment by progrape** [comment]
@CharlesSong v1.3.0 版本支持拖拽浮层了

**Comment by Maizify** [comment]
同上，v1.3.0已经支持拖拽了，不必担心挡住右下角位置。先关闭咯。
