### ISSUE TITLE
右下角按钮支持拖拽

### ISSUE THREAD

**Issue by Treri** [WechatFE/vConsole#2]
目前按钮固定在右下角, 可能会对正常的页面元素造成遮挡无法进行点击

**Comment by raphealguo** [comment]
@Treri 这个问题确实存在。目前可以通过滚动页面来让正常元素避开按钮区域，后续我们讨论解决方案。

**Comment by Treri** [comment]
@raphealguo 滚动页面可以解决部分问题, 其它部分可以通过滚动避开按钮区域, 页面底部由于没法继续往上滚动了, 所以会被一直遮挡. 目前这个还可以接受 😀
