### ISSUE TITLE
建议增加输出时间，并考虑可以导出日志

### ISSUE THREAD

**Issue by huigesv123** [WechatFE/vConsole#20]

**Comment by Maizify** [comment]
考虑到 log 一般都是自己主动打出来的，开发者会知道打印的时机，输出时间感觉作用不大？

**Comment by huigesv123** [comment]
我用这个工具做app HYBIRD日志工具，有记录时间会比较好，虽然可以自己改一下，同时最好可以导出一下

**Comment by Maizify** [comment]
以何种形式导出？

**Comment by huigesv123** [comment]
文件的形式会比较好

**Comment by Maizify** [comment]
先加入到 ToDoList，预计会以插件形式集成起来。

**Comment by Maizify** [comment]
v2.0.0 中已加入 log 打印时间。导出功能就交由插件来做吧，急着用的话可以先自行做个插件哈。先 close 咯。
