### ISSUE TITLE
华为meta7显示异常

### ISSUE THREAD

**Issue by jian263994241** [WechatFE/vConsole#22]
如题

**Comment by Maizify** [comment]
是怎样的异常，可否提供截图？

**Comment by jian263994241** [comment]
![img_0264](https://cloud.githubusercontent.com/assets/2673531/15596592/65194bac-23fb-11e6-9903-907042581652.JPG)

**Comment by jian263994241** [comment]
折叠特别难点中~

**Comment by Maizify** [comment]
必须点击第一行才能展开/收起折叠

**Comment by jian263994241** [comment]
就是点第一行点不中 ....   其他三星上面没问题

**Comment by Maizify** [comment]
我看看怎么把点击区域加大一点吧……

**Comment by zswang** [comment]
因为部分手机的 localStorage 被阉割了。#31

**Comment by Maizify** [comment]
v2.0.1已优化。
