### ISSUE TITLE
按钮位置建议存session

### ISSUE THREAD

**Issue by jian263994241** [WechatFE/vConsole#23]
手贱把按钮 拖拽出屏幕后  找不回来了 ..需要手动删除 local 数据

建议存session 这样 每次打开 按钮位置 就复原了 ...

**Comment by Maizify** [comment]
可以有。现阶段先手动删localstorage吧

**Comment by Maizify** [comment]
v2.0.0 中对拖拽位置做了限定，不会再拖出屏幕外了。
