### ISSUE TITLE
发现有时候 会拦截ajax 请求

### ISSUE THREAD

**Issue by jian263994241** [WechatFE/vConsole#24]
vconsole 会导致 某些ajax 请求 触发 error 错误.  框架用的 Framework7  

偶尔 还有  ajax 请求 发不出去 情况

**Comment by Maizify** [comment]
可否具体一些，是怎样的 ajax 会触发上述情况？

**Comment by jian263994241** [comment]
安卓 华为meta7    https 请求   

ios不存这个问题

**Comment by Maizify** [comment]
是在 meta7 上的所有 https 请求都会被拦截吗？其他安卓机型是否有此问题呢？

**Comment by jian263994241** [comment]
嗯 .偶尔会拦截  没找出拦截特征 
发生的安卓机型上面 
三星之类的也有这个现象

**Comment by Maizify** [comment]
好的，我检查下代码看看。

**Comment by Maizify** [comment]
现在更新到 v2.0.0 再试试看拦截会不会再次发生？
