### ISSUE TITLE
_mokeAjax 会导致同步的ajax失效

### ISSUE THREAD

**Issue by huixisheng** [WechatFE/vConsole#28]
一开始页面发了异步请求，后面又发同步请求。导致同步请求失效，同步请求变成了异步请求

**Comment by Maizify** [comment]
应该是代码里用 `setTimeout` 强制将请求变成了异步，有待下版本修复。

**Comment by jian263994241** [comment]
我也正想说这个问题 ....  我的同步ajax 也失效了   影响比较大哦

**Comment by Maizify** [comment]
下一版本马上修复……

**Comment by Maizify** [comment]
v2.0.0 已修复。
