### ISSUE TITLE
希望把window.onerror的log也打印出来

### ISSUE THREAD

**Issue by 90arther** [WechatFE/vConsole#3]
目前是主动的打印log，如果监听window.onerror事件，把log也打印出来，那就更容易debug了

**Comment by raphealguo** [comment]
@90arther 后续会有考虑加入这个支持，一期考虑是cdn域名和主域名不在一期，onerrror没信息，但其实大部分第三方业务还是没有cdn域名，我们内部讨论后会加入这个支持

**Comment by Maizify** [comment]
v1.1.0已支持。

**Comment by 90arther** [comment]
用起来很赞，感谢
