### ISSUE TITLE
能在weiview打开么？

### ISSUE THREAD

**Issue by wuxingjiang** [WechatFE/vConsole#32]

**Comment by Maizify** [comment]
只要是网页，都可以加载 vConsole。

**Comment by wuxingjiang** [comment]
在webview页面需要app做什么配置么？出现了vconsole按钮但是点上去没反应。

**Comment by Maizify** [comment]
不需要做什么配置，按钮绑定的是 click 事件，理论上点击后就会弹出面板。按钮现在可以拖拽位置吗？

**Comment by wuxingjiang** [comment]
不能。没任何反应，在原生浏览器上是可以的，

**Comment by Maizify** [comment]
是 iOS 还是 Android 的 webview 呢？可否连到电脑看看控制台有无报错信息？

**Comment by wuxingjiang** [comment]
Android 的我试试看有无报错

**Comment by wuxingjiang** [comment]
报错了
![image](https://cloud.githubusercontent.com/assets/15045361/15844284/9360dff4-2c9b-11e6-83ff-a338a69c1acf.png)

**Comment by Maizify** [comment]
OK，明白了，localStorage 在这个 webview 被阉割掉了，已知问题，下一个版本会修复哈。
临时解决办法是，在 vconsole.min.js 中，搜索 `localStorage`，将其所在的两个花括号内的内容先删掉：
`e="vConsole_"+e,localStorage.setItem(e,t)`
`return e="vConsole_"+e,localStorage.getItem(e)`

**Comment by wuxingjiang** [comment]
OK。不会影响功能吧

**Comment by Maizify** [comment]
不影响主要功能，只是记不住按钮拖拽的位置而已。

**Comment by wuxingjiang** [comment]
好的，谢谢。

**Comment by Maizify** [comment]
v2.0.1已修复。
