### ISSUE TITLE
不支持微信浏览器

### ISSUE THREAD

**Issue by jgl5981** [WechatFE/vConsole#37]
不支持微信浏览器,魅族MX4 微信6.3.18

**Comment by Maizify** [comment]
可否提供系统型号、微信版本号等信息？

**Comment by zhongxia245** [comment]
小米4c    微信6.3.18 不行

**Comment by dd1994** [comment]
@zhongxia245 我的也是小米 4c 微信6.3.18 可以正常使用啊

**Comment by deepcoldy** [comment]
三星s7 edge 微信6.3.18 也是无法正常使用，看不到console按钮。

**Comment by Maizify** [comment]
我这里的小米4c+微信6.3.18是可以的，麻烦楼上的朋友们确定一下使用的vConsole是否是最新release的版本？
https://github.com/WechatFE/vConsole/releases/latest
目前github首页显示的是dev分支的版本，里头的版本号虽然仍是v2.0.0，但实际上仍在开发中，实际环境需使用master里的版本。

**Comment by jiangchangjin** [comment]
小米4+微信6.3.18看不到console按钮，但是在其他手机浏览器上是正常的

**Comment by dd1994** [comment]
@jiangchangjin 是不是被那个微信默认的缩小放大按钮遮住了没看到。。。meta 里面禁止缩放试试。

**Comment by jiangchangjin** [comment]
@dd1994 页面上加咯`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">`

**Comment by raphealguo** [comment]
@jiangchangjin 有外网地址提供我们这边看看？

**Comment by jiangchangjin** [comment]
@raphealguo 没有哦，我是本地测试的

**Comment by jiangchangjin** [comment]
@raphealguo 就是demo页面右下角也没有按钮

**Comment by raphealguo** [comment]
@jiangchangjin 方便把你的html页面及其相关资源打包发我们一份看看吗  邮箱：raphealguo[@]qq.com （请自己去掉[]）

**Comment by Maizify** [comment]
在X5内核下有点兼容性问题，v2.0.1已修复。
