### ISSUE TITLE
Android 手Q内置浏览器、Android系统浏览器、Android QQ浏览器里都无法使用

### ISSUE THREAD

**Issue by skyaspnet** [WechatFE/vConsole#38]
Android 手Q内置浏览器、Android系统浏览器、Android QQ浏览器里都无法使用vConsole，iOS下正常，定位到vConsole.min.js里有一行代码：

"complete" == document.readyState ? o() : u["default"].bind(window, "load", o)

执行时会报如下错误：

Symbol is not defined

华为Mate8 手Q最新版，请官方同学及时修复一下，谢谢！

**Comment by Maizify** [comment]
感谢定位错误，我这边抓紧看一下。

**Comment by Maizify** [comment]
v2.0.1已修复。
