### ISSUE TITLE
在红米机子上会报错

### ISSUE THREAD

**Issue by whxaxes** [WechatFE/vConsole#40]
rt

![image](https://cloud.githubusercontent.com/assets/5856440/16147450/c34d6512-34b5-11e6-85da-35a25d77222c.png)

**Comment by Maizify** [comment]
请问用的是哪个vConsole版本？

**Comment by whxaxes** [comment]
2.0.1，直接在你们仓库里的dist目录下copy过来的

**Comment by Maizify** [comment]
修了下，更新到了 dev 分支中，版本号变成 v2.0.2-pre，麻烦下载 dev 分支下的 `dist/vconsole.min.js` 再试试看？

**Comment by whxaxes** [comment]
非常感谢！！

![image](https://cloud.githubusercontent.com/assets/5856440/16186071/f089d910-36fa-11e6-88ae-19a2f16015f1.png)

尝试了一下，用是可以用了，不过还是会抛出异常，可能跟我用了browser-sync的原因有关

我看了一下，发现错误出在了这一行，排查是发现获取xhr的status属性的时候抛的错
![image](https://cloud.githubusercontent.com/assets/5856440/16186425/00136caa-36fd-11e6-99a5-aa388ae01125.png)

然后在stackoverflow上看到
![image](https://cloud.githubusercontent.com/assets/5856440/16186483/576a6472-36fd-11e6-807a-5e8fb3a362f6.png)

然后我改成这样就正常了
![image](https://cloud.githubusercontent.com/assets/5856440/16186515/8284a712-36fd-11e6-9825-9b2b1045562a.png)

仅供参考

**Comment by Maizify** [comment]
好的，感谢反馈！
