### ISSUE TITLE
为什么在有的机型 移动vconsole位置 vconsole消失 然后出现不了

### ISSUE THREAD

**Issue by xflife** [WechatFE/vConsole#48]
ex：iPhone 6s ，XiaoMi Note LTE

**Comment by Maizify** [comment]
请问分别用的是什么浏览器？

**Comment by xflife** [comment]
微信内置的浏览器....

**Comment by Maizify** [comment]
只要拖动按钮就会必现吗？我这边重现不出来……只要拖动按钮就会必现吗？我这边重现不出来……

**Comment by xflife** [comment]
我的页面下面有个一个fixed菜单（flex布局） 好像一拖动vconsole 到我fixed的下面去了

**Comment by Maizify** [comment]
原来如此。看来vConsole的z-index要设得更大一些。

**Comment by xflife** [comment]
应该是这个原因，再问如果加入preserve log 这个功能是不是很麻烦

**Comment by Maizify** [comment]
这个功能可以琢磨一下，谢谢反馈哈。

**Comment by xflife** [comment]
谢谢共享撒。^_^
