### ISSUE TITLE
希望能在控制台输入代码进行调试，目前只能修改页面输出，但微信页面缓存很久，刷新困难

### ISSUE THREAD

**Issue by saobee** [WechatFE/vConsole#5]

**Comment by Maizify** [comment]
有这个想法哈，不过还要再规划一下策略，保证安全性。

**Comment by wuyanwen** [comment]
微信页面缓存很久，刷新困难

**Comment by wuyanwen** [comment]
求方案

**Comment by rockjava** [comment]
微信的页面缓存真是太烦人了，但是使用微信web开发者工具中的移动调试，就可以解决这个问题

**Comment by progrape** [comment]
x5 blink 内核已经升级完毕，使用的是标准缓存策略，顽固缓存问题已经解决了

**Comment by saobee** [comment]
我调试的时候刷新办法是在当前页尾部加上随机时间戳参数，可以刷新页面，至于css和js，也只能在尾部加参数刷新

**Comment by xiaoyu2er** [comment]
恩 资源文件尾部加hash就好了 毕竟标准缓存也会缓存

**Comment by Maizify** [comment]
v2.0.0 已加入控制台输入命令的功能。
