### ISSUE TITLE
点console里面的展开，然后就挂了

### ISSUE THREAD

**Issue by memotail** [WechatFE/vConsole#54]
点击可展开的json,然后就全部功能包括关闭，都失效。

返回的是redux log的内容，PC、iphone都失效，其他没测试

fastclick 提示

Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Comment by Maizify** [comment]
谢谢反馈，我这边先定位下问题。

**Comment by Maizify** [comment]
@memotail 可否贴以下代码？我这边重现不出来。

**Comment by memotail** [comment]
@Maizify 不好意思，我这个是整个工程打包的，很难贴代码，主要是使用了react,redux,webpack,fastclick，我初步估计是不是不支持redux-log的log方式，一组一组的，点开一组的展开就出错了。

**Comment by Maizify** [comment]
那看来可能不是fastclick的问题。现在v2.3.1版本依旧是这样？

**Comment by memotail** [comment]
@Maizify 我使用v2.4.0版本已经没问题了，谢谢。
