### ISSUE TITLE
getFoldedLine函数中有一个console.log('123')

### ISSUE THREAD

**Issue by chaiyanlin** [WechatFE/vConsole#59]
我是用npm 安装的，老是在console中出现这个123，不清楚.min.js中有没有这个现象
```
 $.bind($.one('.vc-fold-outer', $line), 'click', function(e) {console.log('123')
```

**Comment by Maizify** [comment]
这是上一个版本的笔误，调试后忘记清除掉了，实在不好意思。可以先手动删除掉这行。

**Comment by chaiyanlin** [comment]
$BVa(B?$B<j(B??$BY\N;R}R}!$2f`J="@'(B??$BN12<E*(B~

?$B<+2fE*(B iPhone

$B:_(B 2016$BG/(B8$B7n(B25$BF|!$>e8a(B10:55$B!$(BMaiz <notifications@github.com<mailto:notifications@github.com>> $B<LF;!'(B


?$B@'>e0lP$HGK\E*(B??$B!$(B??$B9!K:(B?$B@6=|Y\N;!$(B?$B:_IT9%0U;W!#2D0J@h<j(B??$B=|Y\(B?$B9T!#(B

-

**Comment by Maizify** [comment]
v2.4.0 已修正。
