### ISSUE TITLE
普通log字体颜色变成白色（显示空行）

### ISSUE THREAD

**Issue by Professor-Z** [WechatFE/vConsole#69]
从V1.X 到 V2.3.0都出现了这个问题
显示空行，选中可见。

同一个设备同一个浏览器查看你们的demo页面是正常的

**Comment by Maizify** [comment]
请问应如何重现这个bug？

**Comment by Professor-Z** [comment]
抱歉 刚刚发现是某处的style将body的color设置为了#fff 。是我们的问题。不过你们也可以强制设置一下字体颜色。
