### ISSUE TITLE
2.5.0出现Uncaught TypeError: Cannot read property 'scrollHeight' of null

### ISSUE THREAD

**Issue by chaiyanlin** [WechatFE/vConsole#76]
vconsole.min.js?0325:formatted:1969 Uncaught TypeError: Cannot read property 'scrollHeight' of null

**Comment by WingMrL** [comment]
Ah, I met this error, too.

**Comment by Maizify** [comment]
收到，有待修复。

**Comment by Maizify** [comment]
@chaiyanlin @WingMrL 请问一下机型及系统是什么？

**Comment by chaiyanlin** [comment]
iPhone 6s iOS 10

发自我的 iPhone

在 2016年10月9日，下午6:45，Maiz <notifications@github.com<mailto:notifications@github.com>> 写道：


@chaiyanlin<https://github.com/chaiyanlin> @WingMrL<https://github.com/WingMrL> 请问一下机型及系统是什么？

―

**Comment by Maizify** [comment]
@chaiyanlin 如何触发？我这边重现不出来的样子。

**Comment by chaiyanlin** [comment]
我明天在项目里试试告诉你~

发自我的 iPhone

在 2016年10月9日，下午6:51，Maiz <notifications@github.com<mailto:notifications@github.com>> 写道：


@chaiyanlin<https://github.com/chaiyanlin> 如何触发？我这边重现不出来的样子。

―

**Comment by chaiyanlin** [comment]
额，最好能加个联系方式，这里有点说不清楚。

**Comment by 327326724** [comment]
修复了么这个问题，引入zepto就会报这个错

**Comment by Maizify** [comment]
@327326724 还在定位问题。现在只要引入了 zepto 就会报这个错误吗？我试下。

**Comment by chaiyanlin** [comment]
我实在vue项目中报错

发自我的 iPhone

在 2016年10月11日，下午12:50，Maiz <notifications@github.com<mailto:notifications@github.com>> 写道：


@327326724<https://github.com/327326724> 还在定位问题。现在只要引入了 zepto 就会报这个错误吗？我试下。

―

**Comment by 327326724** [comment]
嗯，我的也是vue项目，引入zepto就会报这个错，但是jquery就不会

**Comment by chaiyanlin** [comment]
我什么都没引入，dom操作都是用框架的机制。

发自我的 iPhone

在 2016年10月11日，下午1:26，warden <notifications@github.com<mailto:notifications@github.com>> 写道：


嗯，我的也是vue项目，引入zepto就会报这个错，但是jquery就不会

―

**Comment by Maizify** [comment]
demo 中也有用到 zepto，但是没有报错。我换 vue 试一下。

**Comment by 327326724** [comment]
我是在vue中用zepto会报错，换成jquery不会

**Comment by Maizify** [comment]
@327326724 @chaiyanlin 两位可否提供更详细的 error 堆栈信息？zepto 自身带有 bug，在 iOS 滚屏操作时很容易触发。目前无法定位出究竟是 vConsole 的问题还是 zepto 的问题。

**Comment by chaiyanlin** [comment]
我想提供截图的，但这里无法上传图片

发自我的 iPhone

在 2016年10月11日，下午7:43，Maiz <notifications@github.com<mailto:notifications@github.com>> 写道：


@327326724<https://github.com/327326724> @chaiyanlin<https://github.com/chaiyanlin> 两位可否提供更详细的 error 堆栈信息？zepto 自身带有 bug，在 iOS 滚屏操作时很容易触发。目前无法定位出究竟是 vConsole 的问题还是 zepto 的问题。

**Comment by Maizify** [comment]
@chaiyanlin 我已发邮件至你 Github 资料页上的邮箱地址，可以邮件交流。

**Comment by spademan** [comment]
+1

**Comment by Maizify** [comment]
@spademan 请问是什么浏览器？可否提供页面网址给我试下呢？

**Comment by spademan** [comment]
@ Maizify因为是内部项目，提供不了地址
 zepto :  v1.1.6 
chrome: 53.0.2785.143 (64-bit)
mac

开启chrome手机模拟器 就能复现

**Comment by FatDong1** [comment]
`vconsole.min.js?v=201807041738:11 Uncaught TypeError: Cannot read property 'scrollHeight' of null
    at t.value (vconsole.min.js?v=201807041738:11)
    at t.value (vconsole.min.js?v=201807041738:11)
    at t.value (vconsole.min.js?v=201807041738:11)
    at e.value (vconsole.min.js?v=201807041738:10)
    at vconsole.min.js?v=201807041738:10
value @ vconsole.min.js?v=201807041738:11
value @ vconsole.min.js?v=201807041738:11
value @ vconsole.min.js?v=201807041738:11
value @ vconsole.min.js?v=201807041738:10
(anonymous) @ vconsole.min.js?v=201807041738:10
setTimeout (async)
value @ vconsole.min.js?v=201807041738:10
(anonymous) @ vconsole.min.js?v=201807041738:10`


是不是因为我把__vconsole元素嵌到iframe的原因？
