### ISSUE TITLE
vConsole会破坏系统原生console.log的显示打log处文件名和行号的行为

### ISSUE THREAD

**Issue by oliverzy** [WechatFE/vConsole#79]
加载了vConsole之后，所有的console.log调用在系统控制台里面显示的文件名和行号都变成了vConsole.min.js:1，而不是显示相应的文件名和行号了

**Comment by Maizify** [comment]
这个似乎并没有很好的办法，要接管 console.log() 行为必然会导致入侵原生设定。
在电脑上调试的时候，可以先不加载 vConsole……

**Comment by memotail** [comment]
可以通过其他方式调试。别用console.log('test'),
1、 改为console.dir('test'),因为vconsole目前没接管console.dir。
2、临时debug的时候，可以使用console.error('test');error会出现堆栈信息，点开就能看到你代码行位置。当然，用完记得删掉，免得红色一篇。

**Comment by oliverzy** [comment]
好吧，看来是不太好解决，能否给vConsole增加一个初始化方法，可以让用户根据情况比如一个url参数来决定是否要启用vConsole，因为页面JS是预先打包好的上传到CDN的

**Comment by memotail** [comment]
我也是使用者，我之前看过代码，发现只要引用就会调用。

但我也是集成在项目中，通过模块化方式引用就好，触发条件，自己控制。如你所需，你可以每次刷新页面时候，添加个判断url，若满足条件，按需引用加载vConsole，就完事了

**Comment by memotail** [comment]
我也是使用者，我之前看过代码，发现只要引用就会调用。

但我也是集成在项目中，通过模块化方式引用就好，触发条件，自己控制。如你所需，你可以每次刷新页面时候，添加个判断url，若满足条件，按需引用加载vConsole，就完事了

**Comment by memotail** [comment]
我也是使用者，我之前看过代码，发现只要引用就会调用。

但我也是集成在项目中，通过模块化方式引用就好，触发条件，自己控制。如你所需，你可以每次刷新页面时候，添加个判断url，若满足条件，按需引用加载vConsole，就完事了

**Comment by memotail** [comment]
我也是使用者，我之前看过代码，发现只要引用就会调用。

但我也是集成在项目中，通过模块化方式引用就好，触发条件，自己控制。如你所需，你可以每次刷新页面时候，添加个判断url，若满足条件，按需引用加载vConsole，就完事了

**Comment by memotail** [comment]
我也是使用者，我之前看过代码，发现只要引用就会调用。

但我也是集成在项目中，通过模块化方式引用就好，触发条件，自己控制。如你所需，你可以每次刷新页面时候，添加个判断url，若满足条件，按需引用加载vConsole，就完事了

**Comment by memotail** [comment]
我也是使用者，我之前看过代码，发现只要引用就会调用。

但我也是集成在项目中，通过模块化方式引用就好，触发条件，自己控制。如你所需，你可以每次刷新页面时候，添加个判断url，若满足条件，按需引用加载vConsole，就完事了

**Comment by memotail** [comment]
我也是使用者，我之前看过代码，发现只要引用就会调用。

但我也是集成在项目中，通过模块化方式引用就好，触发条件，自己控制。如你所需，你可以每次刷新页面时候，添加个判断url，若满足条件，按需引用加载vConsole，就完事了

**Comment by memotail** [comment]
我也是使用者，我之前看过代码，发现只要引用就会调用。

但我也是集成在项目中，通过模块化方式引用就好，触发条件，自己控制。如你所需，你可以每次刷新页面时候，添加个判断url，若满足条件，按需引用加载vConsole，就完事了

**Comment by memotail** [comment]
我也是使用者，我之前看过代码，发现只要引用就会调用。

但我也是集成在项目中，通过模块化方式引用就好，触发条件，自己控制。如你所需，你可以每次刷新页面时候，添加个判断url，若满足条件，按需引用加载vConsole，就完事了

**Comment by raphealguo** [comment]
@oliverzy 这个参数你可以自己定义，例如用php的话（其他语言同理，自己判断参数之后再输出到html里边）:
<?php 
  if ($_GET['vconsole'] == '1'){
    echo '<script src="vconsole.js"></script>'; 
  }
?>

**Comment by XinChou16** [comment]
Chrome 设置中的 ignore List 添加配置即可,添加这一项:`/vconsole\-3\.3\.4\.min\.js\b`
![image](https://user-images.githubusercontent.com/24493056/122314462-d0a5fa00-cf4a-11eb-9bcd-875b02ec462f.png)
