### ISSUE TITLE
webpack 插件

### ISSUE THREAD

**Issue by diamont1001** [WechatFE/vConsole#83]
`vConsole` 是个好东西，感谢开源！

刚写了个 vconsole 的 webpack 插件，自动在 entry 入口帮忙添加 vconsole 模块，可以不用动业务代码的情况下，自动在开发环境下打开 vconsole 调试模块的效果，当然需要通过 webpack 配置线上环境关闭该插件，具体有描述。

链接：https://github.com/diamont1001/vconsole-webpack-plugin

**Comment by Maizify** [comment]
谢谢支持~
