### ISSUE TITLE
在手机淘宝里面，展开vConsole，再关闭之后就不能点了，也不能拖动；

### ISSUE THREAD

**Issue by liubin595338764** [WechatFE/vConsole#84]
在手机淘宝里面，展开vConsole，再关闭之后就不能点了，也不能拖动；
demo里面也是一样的问题；

**Comment by liubin595338764** [comment]
vc-mask没有隐藏成功，把所有元素都挡住了

**Comment by Maizify** [comment]
请问是什么机型、系统版本？iOS 10.2 中淘宝 6.2.1 无问题。
