### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by stylehuan** [WechatFE/vConsole#85]

**Comment by stylehuan** [comment]
可以增加个配置，默认出现在端的位置。因为要拖动肯定是因为有遮挡

**Comment by Maizify** [comment]
"默认出现在端的位置"是啥意思？

**Comment by stylehuan** [comment]
我没描述清楚，意思是可以配置默认的position ,

**Comment by Maizify** [comment]
可以有。

**Comment by yyman001** [comment]
建议可以跟pc页面同步打印信息

**Comment by Maizify** [comment]
@yyman001 log会同时在vConsole和电脑控制台里显示的。

**Comment by jackqqxu** [comment]
默认在引入vconsole的时候，能不能不要默认展示console的框？只有代码中有console.xxx()调用的时候再展示，这样不打扰用户；

**Comment by Maizify** [comment]
@jackqqxu 目前还做不到，正在考虑这方面的支持。不过，在用户可用到的生产环境，建议不要加载 vConsole。

**Comment by jackqqxu** [comment]
好吧，如果被带到外网去，容易被坑。。。

**Comment by jackqqxu** [comment]
另外想确认下，有没有办法打印出当前执行的行数和列数？

**Comment by Maizify** [comment]
@jackqqxu 比较麻烦，而且会有比较严重的性能问题，暂不考虑。
