### ISSUE TITLE
网络请求一直Pending

### ISSUE THREAD

**Issue by crixusshen** [WechatFE/vConsole#94]
请问这是什么现象？
![image](https://cloud.githubusercontent.com/assets/11752878/24451009/b52d6538-14af-11e7-905c-450b416996b0.png)

**Comment by Maizify** [comment]
已知bug，这里没能获取到XHR状态的变化。

**Comment by crixusshen** [comment]
那怎么解决这个问题？

**Comment by Maizify** [comment]
请等待vConsole修复。

**Comment by crixusshen** [comment]
是不是2.5.2有这个问题？之前的是不是好的？项目急用中

**Comment by Maizify** [comment]
一直都有这个问题。

**Comment by Maizify** [comment]
这个问题是比较蛋疼，建议你买先另寻办法了……

**Comment by crixusshen** [comment]
好吧等待更新，谢谢你了
